### PR TITLE
Italian translation and fix

### PR DESCRIPTION
**Pull request by Mte90**

### CODE REVIEW

**Comment by Mte90** [comment]
any news?

**Comment by groovecoder** [comment]
Sorry I'm slow on this. @Mte90 - would you like write access to this repo and access to publish new releases to the WordPress plugin index?

**Comment by Mte90** [comment]
Okay! Is not a problem for me follow this project :-D

**Comment by groovecoder** [comment]
Cool, I invited you so you can merge pull requests. I'd like to spot check the latest code myself before we make it an official release on the WordPress index.

**Comment by Mte90** [comment]
Okay!
i think that the next steps are merge all the pull requests not approved.

**Pull request merged**
