### PR TITLE
Fix dennis linting .po warning

### PR DESCRIPTION
**Pull request by robhudson**
Fixes W502: multiple variables with no name to allow for localizers to swap variables in their locale if needed.

### CODE REVIEW

**Comment by robhudson** [comment]
Please verify this still works for me. I don't have access to PHP to test myself.

**Comment by Mte90** [comment]
that lines is for add link for widget and settings page that not require a translation

**Comment by robhudson** [comment]
If it doesn't need translation why is it wrapped in the gettext `__` function? Since we copy these strings into MDN it is being flagged in our linter as a warning.

**Comment by Mte90** [comment]
because we inject that urls in the string but I can add that pr.

**Comment by robhudson** [comment]
I see what you're saying. But if the localizer needed to reverse the order of the links for whatever reason (RTL languages?) they would not be able to -- the settings would get the widget link and the widget would get the settings link.

**Comment by Mte90** [comment]
All the language files need to updated only for that but is not a problem :-)

**Pull request merged**
